build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "fmt/3.0.1"
    CONAN_USERNAME: "memsharded"
    CONAN_CHANNEL: "testing"
    CONAN_TOTAL_PAGES: 1

    matrix:
        - CONAN_CURRENT_PAGE: 1

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools==0.2.16 # It install conan too
  - pip.exe install conan --upgrade
  - conan user # It creates the conan data directory

test_script:
  - python build.py
